CREATE TABLE IF NOT EXISTS ACCOUNT (
    ID numeric AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME varchar(32) NOT NULL,
    PASS varchar(128) NOT NULL,
    MAIL varchar(128) NOT NULL,
    LOC varchar(10) NOT NULL,
    BORN varchar(8) NOT NULL,
    ZIP varchar(20) NOT NULL,
    GEND varchar(1) NOT NULL,
    SPAM varchar(2) NOT NULL,
    TOS numeric NOT NULL,
    TICK varchar(128) NOT NULL,
    GAMECODE varchar(20) NOT NULL,
    VERS varchar(32) NOT NULL,
    SKU varchar(10) NOT NULL,
    SLUS varchar(10) NOT NULL,
    SDKVERS varchar(20) NOT NULL,
    BUILDDATE varchar(20) NOT NULL,
    CREATED_ON timestamp NOT NULL,
    UPDATED_ON timestamp NULL
);

CREATE TABLE IF NOT EXISTS PERSONA (
    ID numeric AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ACCOUNT_ID numeric NOT NULL,
    PERS varchar(32) NOT NULL,
    KILLS numeric NOT NULL DEFAULT 0,
    DEATHS numeric NOT NULL DEFAULT 0,
    RP numeric NOT NULL DEFAULT 5,
    CREATED_ON timestamp NOT NULL,
    DELETED_ON timestamp NULL,
    CONSTRAINT FK_PERSONA_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);

CREATE TABLE IF NOT EXISTS CONNECTIONS (
    ID numeric AUTO_INCREMENT PRIMARY KEY NOT NULL,
    IP varchar(255) NOT NULL,
    ACCOUNT_ID numeric NULL,
    START_TIME timestamp NOT NULL,
    LAST_PING timestamp NOT NULL,
    END_TIME timestamp NULL,
    CONSTRAINT FK_CONNECTIONS_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);

CREATE TABLE IF NOT EXISTS LOBBY (
    ID numeric AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME varchar(32) NOT NULL,
    PARAMS varchar(255) NOT NULL,
    SYSFLAGS varchar(10) NOT NULL,
    START_TIME timestamp NOT NULL,
    END_TIME timestamp NULL
);

CREATE TABLE IF NOT EXISTS LOBBY_PERSONA (
    ID numeric AUTO_INCREMENT PRIMARY KEY NOT NULL,
    LOBBY_ID numeric NOT NULL,
    PERSONA_ID numeric NOT NULL,
    KILLS numeric NOT NULL DEFAULT 0,
    DEATHS numeric NOT NULL DEFAULT 0,
    IN_LOBBY boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT FK_LOBBY_REPORT_LOBBY_ID FOREIGN KEY (LOBBY_ID) REFERENCES LOBBY(ID),
    CONSTRAINT FK_LOBBY_REPORT_PERSONA_ID FOREIGN KEY (PERSONA_ID) REFERENCES PERSONA(ID)
);
